### ISSUE TITLE
終日予定に対応できていない

### ISSUE THREAD

**Issue by takanamito** [masayukinagayama/imananishiton#3]
終日予定が入っていると、その日はずっとその予定を表示してしまう。
終日予定は無視して時間指定の予定だけslack statusに反映したい。

**Comment by sak0620** [comment]
events[1]
を
events[(events.length - 1)]
に変えるといけるね。

**Comment by sak0620** [comment]
っとおもったけど、終日予定を無視というのは上のままじゃいけないな。

**Comment by takanamito** [comment]
CalenderEventオブジェクトに終日判定返すメソッド発見
たぶんこれでいける

Class CalendarEvent  |  Apps Script  |  Google Developers
https://developers.google.com/apps-script/reference/calendar/calendar-event#isAllDayEvent()

**Comment by masayukinagayama** [comment]
対応出来ました。DONE !!
